/* eslint-disable react/no-unescaped-entities */
import "./style.scss";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { loginUser } from "../../services/http-request";
import { toast } from "react-toastify";
import LoginCardView from "../../components/LoginCardView";
import { getCookie, setCookie } from "../../utils/setCookie";

const INITIAL_VALUE = {
  username: "",
  password: "",
};


/**
 * @description Is a React component that renders a login form and handles user input,
 * submission, and authentication through the `loginUser` API endpoint. It also stores
 * cookies for token and username after successful authentication.
 * 
 * @returns { object } a HTML page with a login form.
 */

const LoginPage = () => {
  const navigate = useNavigate();
  const [formValue, setFormValue] = useState(INITIAL_VALUE);
  const token = getCookie("token");

  useEffect(() => {
    if (token) {
      navigate("/");
    }
  }, []);

  /**
   * @description Updates the value of a form's field by setting the corresponding
   * property of an object called `formValue` using the event target's name and value.
   * 
   * @param { object } event - Event Object that triggered the function, providing the
   * current value of the form field being processed.
   */

  const handleOnChange = (event) => {
    setFormValue({ ...formValue, [event.target.name]: event.target.value });
  };

  /**
   * @description Preventdefault and stop form from being submitted. It then logs in a
   * user using `loginUser` method, passing in form values as arguments. If the login
   * is successful, it sets cookies for `token` and `username`, shows a toast message,
   * and navigates to the root URL. Otherwise, it shows an error toast message.
   * 
   * @param { Event. } e - Event object generated by clicking the login button and
   * prevents the default behavior of the click event.
   * 
   * 	* `preventDefault()` is a function that prevents the default form submission behavior.
   * 	* `try` block executes code within it when `loginUser()` promise resolves.
   * 	* `loginUser()` is a function that performs login actions, and its response is
   * caught in the `then` block.
   * 	* `res.json()` is a method that extracts JSON data from a resolved promise.
   * 	* `data` is the JSON data extracted from the promise using `res.json()`.
   * 	* `token` is a property of the `data` object, indicating successful login.
   * 	* `username` is another property of the `data` object, representing the logged-in
   * user's username.
   * 	* `toast` is an instance of `Toast` class, used for displaying informative messages
   * to the user.
   * 	* `navigate()` is a function that changes the current page's URL.
   * 
   * @returns { object } a JSON object containing a token and username, or an error
   * message if there is an issue with the login process.
   */

  const onSubmitHandler = async (e) => {
    e.preventDefault();
    try {
      loginUser(formValue)
        .then(function (res) {
          return res.json();
        })
        .then(function (data) {
          if (data.token) {
            setCookie("token", data.token, 15);
            setCookie("username", data.username, 15);
            toast.success("User LoggedIn Successfully!");
            navigate("/");
          } else {
            toast.error(JSON.stringify(data));
          }
        });
    } catch (error) {
      console.error("Error:", error);
      toast.error(JSON.stringify(error));
    }
  };

  return (
    <LoginCardView
      title="Login Page"
      subTitle="Welcome to Homecare Login Page. Please enter your details to
                  sign in to your account!"
    >
      <div className="d-flex justify-content-end">
        <span className="py-3 dashboard-container__introduction__already_account_text">
          Don't have an account? <a href="/register">Register here</a>
        </span>
      </div>
      <form onSubmit={onSubmitHandler}>
        <div className="mb-3">
          <label className="form-label">Username</label>
          <input
            type="text"
            name="username"
            className="form-control form-control-lg"
            placeholder="Enter your username"
            onChange={handleOnChange}
            required
          />
        </div>
        <div className="mb-3">
          <label className="form-label">Password</label>
          <input
            type="password"
            name="password"
            className="form-control form-control-lg"
            id="passwordInput"
            onChange={handleOnChange}
            placeholder="Enter Password"
            required
          />
        </div>
        <input
          className="btn btn-primary btn-lg w-100 mt-2"
          type="submit"
          value="Sign In"
        />
      </form>
      <span className="py-3 dashboard-container__introduction__already_account_text">
        <a href="/forgot-password"> Forgot Password?</a>
      </span>
    </LoginCardView>
  );
};

export default LoginPage;
