/* eslint-disable react/no-unescaped-entities */
import { useState } from "react";
// import { registerUser } from "../../services/http-request";
import { useNavigate } from "react-router-dom";
import LoginCardView from "../../components/LoginCardView";
import { registerUser } from "../../services/http-request";
import { toast } from "react-toastify";

const INITIAL_VALUE = {
  email: "",
  username: "",
  first_name: "",
  last_name: "",
  password: "",
  password2: "",
  gender: "",
  age: 0,
  phone: "",
  address: "",
};


/**
 * @description Generates high-quality documentation for code provided and returns a
 * React component for the register page, which includes a form for entering user
 * information and a submit button.
 * 
 * @returns { string } a React component for user registration.
 */

const RegisterPage = () => {
  const navigate = useNavigate();
  const [formValue, setFormValue] = useState(INITIAL_VALUE);


  /**
   * @description Updates the `formValue` object by setting the value of each form field
   * to its corresponding event target's value.
   * 
   * @param { object } event - current form value being edited by the user.
   */

  const handleOnChange = (event) => {
    setFormValue({ ...formValue, [event.target.name]: event.target.value });
  };


  /**
   * @description Preventdefault, try and catch block ensure the form data is submitted
   * to the server for processing, handling potential errors or success messages accordingly
   * 
   * @param { event. } e - Event object generated by the form's submit event, which the
   * function handles to prevent the default submission behavior and perform its own actions.
   * 
   * 	* `e.preventDefault()` - prevents the default form submission behavior
   * 	* `registerUser(formValue)` - function to be executed when preventing the default
   * form submission behavior
   * 		+ `formValue` - a value passed as an argument to the `registerUser()` function,
   * representing the form input values
   * 		+ Returns a promise resolving to JSON data
   * 		+ The resulting JSON data is passed as a callback argument to the `.then()` method
   * 	* `toast.success(JSON.stringify(data.message))` - displays a successful registration
   * message in the toast notification area
   * 		+ `data.message` - the message to display in the toast notification area, returned
   * by the promise resolved from `registerUser()`
   * 		+ The message is serialized to JSON format using `JSON.stringify()`
   * 	* `setFormValue(INITIAL_VALUE)` - sets a new value for the form input fields to
   * their initial state
   * 	* `navigate("/login")` - navigates the user to the login page
   * 
   * 	The `try` block is used to handle potential errors that may occur during the
   * execution of the function. If an error occurs, it is logged to the console using
   * `console.error()` and a toast notification is displayed using `toast.error()`.
   * 
   * @returns { array } a successful registration of a new user, accompanied by a toast
   * notification with a success message or an error message if any.
   */

  const onSubmitHandler = async (e) => {
    e.preventDefault();
    try {
      registerUser(formValue)
        .then(function (res) {
          return res.json();
        })
        .then(function (data) {
          if (data.message) {
            toast.success(JSON.stringify(data.message));
            setFormValue(INITIAL_VALUE);
            navigate("/login");
          } else {
            toast.error(JSON.stringify(data));
          }
        });
    } catch (error) {
      console.error("Error:", error);
      toast.error(JSON.stringify(error));
    }
  };

  return (
    <LoginCardView title="User Registration" subTitle="">
      <form onSubmit={onSubmitHandler}>
        <div className="mb-3 d-flex">
          <div className="col-6">
            <label className="form-label">First Name</label>
            <input
              type="text"
              name="first_name"
              maxLength="50"
              className="form-control form-control-lg"
              placeholder="Enter your first name"
              onChange={handleOnChange}
              required
            />
          </div>
          <div className="col-6 pl-5">
            <label className="form-label">Last Name</label>
            <input
              type="text"
              name="last_name"
              maxLength="50"
              className="form-control form-control-lg"
              placeholder="Enter your last name"
              onChange={handleOnChange}
              required
            />
          </div>
        </div>
        <div className="mb-3 d-flex">
          <div className="col-6">
            <label className="form-label">Age</label>
            <input
              type="number"
              name="age"
              className="form-control form-control-lg"
              id="pageInput"
              onChange={handleOnChange}
              placeholder="Enter Your Age"
            />
          </div>
          <div className="col-6 pl-5">
            <label className="form-label">Gender</label>
            <select
              className="form-select form-select-lg"
              name="gender"
              aria-label="Select Your Gender"
              onChange={handleOnChange}
              placeholder="Select your Gender"
            >
              <option selected>Select Your Gender</option>
              <option value="female">Female</option>
              <option value="male">Male</option>
              <option value="other">Other</option>
            </select>
          </div>
        </div>
        <div className="mb-3 d-flex">
          <div className="col-6">
            <label className="form-label">Phone Number</label>
            <input
              type="text"
              name="phone"
              maxLength="14"
              className="form-control form-control-lg"
              id="phoneInput"
              onChange={handleOnChange}
              placeholder="Enter Your Phone Number"
            />
          </div>
          <div className="col-6 pl-5">
            <label className="form-label">Address</label>
            <input
              type="text"
              name="address"
              maxLength="50"
              className="form-control form-control-lg"
              placeholder="Enter your address"
              onChange={handleOnChange}
              required
            />
          </div>
        </div>
        <div className="mb-3 d-flex">
          <div className="col-6">
            <label className="form-label">Username</label>
            <input
              type="text"
              name="username"
              maxLength="50"
              className="form-control form-control-lg"
              placeholder="Enter username"
              onChange={handleOnChange}
              required
            />
          </div>
          <div className="col-6 pl-5">
            <label className="form-label">Email</label>
            <input
              type="text"
              name="email"
              maxLength="50"
              className="form-control form-control-lg"
              placeholder="Enter your email"
              onChange={handleOnChange}
              required
            />
          </div>
        </div>
        <div className="mb-3 d-flex">
          <div className="col-6">
            <label className="form-label">Password</label>
            <input
              type="password"
              name="password"
              maxLength="50"
              className="form-control form-control-lg"
              id="passwordInput"
              onChange={handleOnChange}
              placeholder="Enter Password"
              required
            />
          </div>
          <div className="col-6 pl-5">
            <label className="form-label">Confirm Password</label>
            <input
              type="password"
              name="password2"
              maxLength="50"
              className="form-control form-control-lg"
              id="password2Input"
              onChange={handleOnChange}
              placeholder="Enter Confirm Password"
              required
            />
          </div>
        </div>
        <input
          className="btn btn-primary btn-lg w-100 mt-2"
          type="submit"
          value="Sign Up"
        />
      </form>
      <span className="py-3 dashboard-container__introduction__already_account_text">
        <>
          {" "}
          Already have an account? <a href="/login">Login here</a>{" "}
        </>
      </span>
    </LoginCardView>
  );
};

export default RegisterPage;
